"""Compatibility re-exports for credential service boundaries."""

from snaplex.credentials import (
    CredentialMissingError,
    CredentialReference,
    CredentialService,
    CredentialSource,
    CredentialStatus,
    CredentialStatusCode,
    CredentialStore,
    CredentialStoreError,
    CredentialUnavailableError,
    CredentialUnsupportedError,
    EnvironmentCredentialStore,
    InMemoryCredentialStore,
    KeyringCredentialStore,
    create_default_credential_service,
    create_environment_credential_service,
    credential_reference_from_dict,
    credential_reference_to_dict,
    environment_credential_reference,
    keyring_credential_reference,
)

__all__ = [
    "CredentialMissingError",
    "CredentialReference",
    "CredentialService",
    "CredentialSource",
    "CredentialStatus",
    "CredentialStatusCode",
    "CredentialStore",
    "CredentialStoreError",
    "CredentialUnavailableError",
    "CredentialUnsupportedError",
    "EnvironmentCredentialStore",
    "InMemoryCredentialStore",
    "KeyringCredentialStore",
    "create_default_credential_service",
    "create_environment_credential_service",
    "credential_reference_from_dict",
    "credential_reference_to_dict",
    "environment_credential_reference",
    "keyring_credential_reference",
]
